### ISSUE TITLE
update()

### ISSUE THREAD

**Issue by AngryElephant** [Yopadd/vue-chartist#12]
Chartist has an update method https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update

Just wonder why it's not used in this component instead of redraw everything each time the data change ?

**Comment by Yopadd** [comment]
Hi,

I tested your proposal. With update method it's not possible to redraw a chart with a new type (Pie, Line, Bar). But with two methods : _draw_ (for type property) and _redraw_ (for other propertys) it's possible and this is certainly more performance.

Thanks for your proposal :)

**Comment by AngryElephant** [comment]
Hello,

Yes if we don't want to transform a Line in Pie or Bar but just update the chart with new data (series, labels) or even options. The update() method can be useful :) 

Thanks for your answer.
