### ISSUE TITLE
Example gives weird painting

### ISSUE THREAD

**Issue by beebase** [Yopadd/vue-chartist#16]
I did a fresh install with vue-loader and added the basic example, but it's painting weird.
Am I missing something?
![image](https://cloud.githubusercontent.com/assets/446089/19302918/be8a71c0-9066-11e6-9f6a-90505eaa9918.png)

**Comment by beebase** [comment]
hmm..looks like vue-loader isn't picking up chartist.css and chartist.js

**Comment by larsmars** [comment]
How did you solve this? I get the same. vue-chartist v. 2.1.2, vue 2.5.16

**Comment by beebase** [comment]
I didn't, 
moved on to https://github.com/ecomfe/vue-echarts. (needed more charts)

**Comment by larsmars** [comment]
Ok thank you, re-open this bug?

**Comment by Flink91** [comment]
I see the same black triangles
