### ISSUE TITLE
Distributed Series

### ISSUE THREAD

**Issue by kJamesy** [Yopadd/vue-chartist#17]
Thanks for the great work.
How would I go about creating a distributed bar series chart as seen here http://gionkunz.github.io/chartist-js/examples.html#example-bar-distributed-series

I get the error: 'serie.data is undefined' whenever I do:
```javascript                
                chartData: {
                    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
                    series: [800000, 1200000, 1400000, 1300000]
                },
                chartOptions: {
                    distributeSeries: true
                },
```

**Comment by Yopadd** [comment]
Hi,
I see the problem. I fix that.

Thank you for your participation :)

**Comment by kJamesy** [comment]
Works perfectly, thanks

**Comment by kJamesy** [comment]
PS: Just a heads-up, there's a stray console.log() on [#43](https://github.com/Yopadd/vue-chartist/blob/master/src/index.js#L43)

**Comment by Yopadd** [comment]
Oh ! yes thanks...
