### ISSUE TITLE
Problem with threshold plugin

### ISSUE THREAD

**Issue by rayoplateado** [Yopadd/vue-chartist#20]
Hi! 

I'm using chartist through vue-chartist. The point is that I want to use the threshold plugin, but if I install it and call into a chart, it said to me `Chartist is not defined`, which is correct, because chartist is in `Vue.chartist`

How can I set `Chartist` value called into the plugin to point to `Vue-chartist` without modify the threshold plugin?

**Comment by Yopadd** [comment]
Hi,

It's complicated, it seems that react-chartist has the same problems.
I will think about it but without guarantee.

**Comment by Yopadd** [comment]
I found a quick ~~dirty~~ tricks.
```js
Vue.use(VueChartist)
Chartist = Vue.chartist
require('chartist-plugin-pointlabels')
Vue.chartist = Chartist

...

options: {
  plugins: [
    Vue.chartist.plugins.ctPointLabels({
      textAnchor: 'middle'
    })
  ]
},
```
I have managed to run _chartist-plugin-pointlabels_ but not _chartist-plugin-threshold_ :confused:
Maybe I badly use _chartist-plugin-threshold_ ...

**Comment by rayoplateado** [comment]
I think I've tried this with no success. Let me test again and I'll let you know!

Thank you @Yopadd!

**Comment by fyyyyy** [comment]
If you want to use it in a subcomponent, you may want to assign in your index.js
`window.Chartist = Chartist`


and in the component you can reference `window.Chartist.plugins`

**Comment by Mathieu-R** [comment]
It doesn't work for me with threshold plugin.
