### ISSUE TITLE
Some issue with axis

### ISSUE THREAD

**Issue by sausin** [Yopadd/vue-chartist#21]
First off - thanks for providing this vue integration! :+1: 

I am having an issue with the way the chart comes up. The x-axis is not coinciding with the y-axis '0'. 

![image](https://cloud.githubusercontent.com/assets/11542923/24578074/3ab7bdea-16d9-11e7-84bf-c35f822e3b7a.png)

What I expect to happen is that 0 should be the same as the baseline. 

The chartdata being passed is as below:

![image](https://cloud.githubusercontent.com/assets/11542923/24578060/ffdcba4a-16d8-11e7-89ed-7af231bfb16d.png)

Thanks!

**Comment by Yopadd** [comment]
Hi,

I have try to reprocduce your issue. But with no succes :(
![image](https://cloud.githubusercontent.com/assets/12082978/24746578/e3f7d348-1ab9-11e7-83a0-f1ddf19ab165.png)
Do you can give me your chart options, ratio and data in details ?

**Comment by sausin** [comment]
@Yopadd Thanks for looking at this!

Something even more strange has happened. It's working correctly now! And I have changed nothing in the code that generated the said graph!

However, I've been changing other things in the javascript webpack compilation so something else (another library) could've been doing something.

I will dig more into this (get the version of my codebase when it was a problem) and post again.

**Comment by sausin** [comment]
@Yopadd I can't recreate the issue at the moment, so I will close it. If it recurs, I will be sure to provide the details which are suspect to have caused this behaviour.

Thanks!
