### ISSUE TITLE
event-handler not working

### ISSUE THREAD

**Issue by AndreaRylander** [Yopadd/vue-chartist#25]
Hi,
is it possible to get a working example on event-handlers??  I can't get it to work in my  single file component.

Thanks in advance!

**Comment by Yopadd** [comment]
Hi,

`event-handlers` is an tag to use [`addEventHandler()`](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistevent-function-addeventhandler).
This functions take two attributes:
- `event` a string (like 'draw')
- `handlers` a function

To use event-handlers attribute in your html
```html
<chartist
    class="chart"
    ratio="ct-square"
    type="Bar"
    :event-handlers="events"
    :data="distributedSeriesData"
    :options="distributedSeriesOptions" >
</chartist>
```
and in your Js `event-handlers` take an array. Items of this array must be objects with two attributes
- `event` a string
- `fn` a function
```javascript
data() {
  return {
    //...
    events: [{
      event: 'draw',
      fn: context => {
        context.element.attr({
          style: `stroke: hsl(${Math.floor(this.$chartist.getMultiValue(context.value) / 100 * 100)}, 50%, 50%);`
        })
      }
    }]
  }
}
```
This example have the same behavior as [USING DRAW EVENTS TO MODIFY CHART ELEMENTS](https://gionkunz.github.io/chartist-js/getting-started.html#colour-up-your-charts).

I have added this example in the repository.
