### ISSUE TITLE
redraw() does not work when sub-item of data-property is updating

### ISSUE THREAD

**Issue by itelmenko** [Yopadd/vue-chartist#27]
In **redraw (newValue, oldValue)**  method I see

```javascript
if (JSON.stringify(newValue) === JSON.stringify(oldValue)) {
          return
}
```

But this condition will always **true**, because newValue == oldValue if sub-item of property was updated.

Here in [documentation](https://vuejs.org/v2/api/#vm-watch):

> Note: when mutating (rather than replacing) an Object or an Array, the old value will be the same as new value because they reference the same Object/Array. Vue doesn’t keep a copy of the pre-mutate value.

So if you even use the **deep** option

```javascript
'data': { handler: 'redraw', deep: true },
```

you cannot compare **newValue** and **oldValue**.

I think you have to remove this condition.

**Comment by Yopadd** [comment]
Thank for your feeback. This condition has been removed to 2.1.2
