### ISSUE TITLE
Strange black background fill the graph

### ISSUE THREAD

**Issue by Mathieu-R** [Yopadd/vue-chartist#29]
Hello !

I'm using vue-chartist in a project using Vue 2 and I have this strange black background which I don't know where it's coming from ?
Is it a known bug ?

![image](https://user-images.githubusercontent.com/16360664/32767425-acb66116-c913-11e7-9c44-92f5b08f147f.png)

Thanks !

**Comment by MartinMuzatko** [comment]
I would like to know where this comes from. have the same problem

**Comment by mamdasan** [comment]
you forgot to add the chartist css file 
[https://gionkunz.github.io/chartist-js/getting-started.html#one-two-three-css](url)

**Comment by theavijitsarkar** [comment]
Please mention how to do that

**Comment by lukecleland-myfiziq** [comment]
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chartist/0.11.4/chartist.min.css" integrity="sha512-V0+DPzYyLzIiMiWCg3nNdY+NyIiK9bED/T1xNBj08CaIUyK3sXRpB26OUCIzujMevxY9TRJFHQIxTwgzb0jVLg==" crossorigin="anonymous" />

**Comment by lukecleland-myfiziq** [comment]
https://cdnjs.cloudflare.com/ajax/libs/chartist/0.11.4/chartist.min.css
