### ISSUE TITLE
NPM package name

### ISSUE THREAD

**Issue by kartsims** [Yopadd/vue-chartist#3]
Hi,

First, thanks for the lib, I am giving it a try right now, it is exactly what I was looking for, so thanks for that !

While importing it to my project, I was thinking that your NPM package name doesn't really looks like other package names, you should probably go for [vue-chartist](https://www.npmjs.com/package/vue-chartist) instead.

Just a suggestion, and I'll let you know if I can improve it in any way, have a great day !

**Comment by Yopadd** [comment]
Yes for sure. I will push v1 and rename the package. Soon ;)
