### ISSUE TITLE
Write something about using plugins in the README

### ISSUE THREAD

**Issue by fonsecas72** [Yopadd/vue-chartist#35]
I'm having some trouble about using plugins and despite I've found some issues about it I couldn't use any. 

I think it would be very useful if this was clear in the README even if it is just to say "you can't use plugins"

Thank you for your work.

**Comment by douglasg14b** [comment]
@Yopadd Any word on this? Would love to hear if we can use plugins or not....

**Comment by PureLines** [comment]
**It's possible to use plugins with vue-chartist.**

There is an example, how to use [chartist-plugin-legend](https://github.com/CodeYellowBV/chartist-plugin-legend):

1. Install plugin: `npm install chartist-plugin-legend --save`.
2. Import plugin and add `plugins` section to Chartist options in your Vue component:
```JS
import Legend from 'chartist-plugin-legend';

export default {
  data() {
    return {
      [...],
      chartOptions: {
        axisX: {...},
        axisY: {...},
        plugins: [
          Legend({
            position: 'top',
          }),
        ],
      },
    },
  },
}
```
3. Add plugin styles (optional, check plugin readme).
