### ISSUE TITLE
Embed Chartist.js in the Vue component

### ISSUE THREAD

**Issue by kartsims** [Yopadd/vue-chartist#5]
Hi,

I am still struggling with this component to get it working without having to include Chartist library as a separate file...

My use case is that I am developing a rather large application with Vue and Vue Router, packaged using Webpack (as per the [webpack vue template](https://github.com/vuejs-templates/webpack)). No static JS asset is supposed to go around the Webpack build workflow so do you know if we could figure out a way to embed the Chartist JS object directly inside the Vue component ?

**Comment by Yopadd** [comment]
Hi,

What do you thinks of this ? Add an option to embed Chartist like this
`npm i --save-dev chartist`
then
```javascript
const Chartist = require('chartist')
Vue.use(require('vue-chartist'), { Chartist })
```
I did a branch *embed-chartist*. If you want see in details.

**Comment by kartsims** [comment]
Could you help me to use your example ? I forked the `embed-chartist` branch but can't do `npm run build` in the example

**Comment by kartsims** [comment]
I get `Error: Couldn't find preset "es2015" relative to directory`

Did you try it by deleting your `example/node_modules` directory, do `npm install` and `npm run build` ? If this works for you it might be due to Node/NPM versions (I run Node 5.4.1 and NPM 3.5.3)

**Comment by kartsims** [comment]
If you want we could discuss it here : https://gitter.im/kartsims/vue-chartist
