### ISSUE TITLE
noData property conflict

### ISSUE THREAD

**Issue by PureLines** [Yopadd/vue-chartist#52]
After this commt https://github.com/Yopadd/vue-chartist/commit/b6cae419763e89ca1e0929d4bf416696053f7ef6 you have conflict between `noData`  component property and `noData` data property.

So I get this error in console after updating to [v2.3.0](https://github.com/Yopadd/vue-chartist/releases/tag/v2.3.0):
`Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "noData"`
with trace to https://github.com/Yopadd/vue-chartist/blob/63c90e72598ebd709280cd6ebe564de1129832c5/src/index.js#L107-L109.

**Comment by binoysarker** [comment]
i am having the same problem. Please let me know which version does not show this error. Thanks.

**Comment by joweste** [comment]
I have the same problem.

**Comment by Yopadd** [comment]
Hi,
It's fixed to 2.3.1
thanks.
