### ISSUE TITLE
useForeignObject

### ISSUE THREAD

**Issue by dmodaii** [Yopadd/vue-chartist#7]
how to set useForeignObject in chartist to be false?
because i want to tansform ForeignObject in svg to canvas , but failed,
so I want to customise this option custom

**Comment by Yopadd** [comment]
Hi,
Do you have a code example with just Chartist for what you trying to do ?

**Comment by dmodaii** [comment]
finally, I find a way to tansform ForeignObject in svg to canvas through 
removeAttr  'xmlns' in 'foreignObject span' for sake of the error about  " reuse namespace "

before svg2canvas:
```javascript
    $(svg).find('foreignObject span').each(function () {
      $(this).removeAttr('xmlns')
    })
```
