### ISSUE TITLE
responsiveOptions expects and Object, but ChartistJS expects an Array

### ISSUE THREAD

**Issue by bdunn313** [Yopadd/vue-chartist#9]
Currently, the responsiveOptions prop expects an Object, but according to the Chartist API, an Array should be passed:

See documentation for Bar or any other chart type:

[Bar chart API docs](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbar-function-bar)

**Comment by Yopadd** [comment]
Oh, ok I merge that.
Thanks :)
